services:
  telegram:
    image: aiogram/telegram-bot-api:latest
    restart: unless-stopped
    environment:
      - SERVICE_URL_TELEGRAM_8984
      - TELEGRAM_API_ID=${TELEGRAM_API_ID:?}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH:?}
      - TELEGRAM_HTTP_PORT=8984
      - TELEGRAM_LOCAL=1
      - TELEGRAM_VERBOSITY=2
      - TELEGRAM_STAT=1
    volumes:
      - telegram-data:/var/lib/telegram-bot-api
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8082/"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 60s
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  watchtower:
    image: nickfedor/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - --schedule
      - "0 0 0 * * *"
      - --label-enable
      - --cleanup
    restart: unless-stopped

volumes:
  telegram-data:
